# Generated by Django 2.0.8 on 2018-12-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180819_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unsubscribe_field',
            field=models.BooleanField(default=True),
        ),
    ]
