# Generated by Django 2.0.8 on 2018-12-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_unsubscribe_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unsubscribe_field',
            new_name='unsubscribe_link',
        ),
    ]
