# Generated by Django 2.0.8 on 2018-12-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181224_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('content', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'Users Notifications',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserNotification'),
        ),
    ]
