# Generated by Django 2.0.8 on 2018-12-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181224_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
