# Generated by Django 2.0.8 on 2018-12-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181224_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unsubscribe_link',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
