# Generated by Django 2.0.8 on 2018-12-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181225_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.BooleanField(default=False, verbose_name='unsubscribe_link'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
