# Generated by Django 2.0.8 on 2018-12-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181225_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='unsubscribe_link',
            field=models.BooleanField(default=False),
        ),
    ]
