# Generated by Django 2.0.8 on 2018-12-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20181225_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unsubscribe_link',
        ),
    ]
